version: "3.7"

services:
  app:
    container_name: ${PROJECT_NAME}
    image: ${PROJECT_NAME}:${PLATFORM_NAME}
    env_file: .env
    build:
      context: ../
      dockerfile: dock-swag/build/Dockerfile
      args:
        - PROJECT_DIR=${PROJECT_DIR}
        - BUILD_DIR=${BUILD_DIR}
        - COMPOSER_HOME=${COMPOSER_HOME}
        - HTTP_HOST=${HTTP_HOST}
        - HTTP_PORT=${HTTP_PORT}
        - DOCKER_USER=${DOCKER_USER}
        - DOCKER_USER_ID=${DOCKER_USER_ID}
        - DOCKER_PROJECT_DIR=${DOCKER_PROJECT_DIR}
    depends_on:
      - mysql
    ports:
      -  "${HTTP_PORT}:8000"
    environment:
      - APP_SECRET=123456789
      - DATABASE_URL=mysql://root:root@mysql:3306/shopware
      - APP_URL=http://${HTTP_HOST}:${HTTP_PORT}
      - MAILER_URL=smtp://localhost:25?encryption=&auth_mode=
    volumes:
      - ../${PROJECT_DIR}/bin:${DOCKER_PROJECT_DIR}/bin
      - ../${PROJECT_DIR}/config:${DOCKER_PROJECT_DIR}/config
      - ../${PROJECT_DIR}/custom:${DOCKER_PROJECT_DIR}/custom
      - ../${PROJECT_DIR}/files:${DOCKER_PROJECT_DIR}/files
      - ../${PROJECT_DIR}/public:${DOCKER_PROJECT_DIR}/public
      - ../${PROJECT_DIR}/src:${DOCKER_PROJECT_DIR}/src
      - ../${PROJECT_DIR}/var/log:${DOCKER_PROJECT_DIR}/var/log
      - ../${PROJECT_DIR}/platform:${DOCKER_PROJECT_DIR}/platform
      - ../${PROJECT_DIR}/composer.json:${DOCKER_PROJECT_DIR}/composer.json
      - ../${PROJECT_DIR}/composer.lock:${DOCKER_PROJECT_DIR}/composer.lock
      - ../.env:${DOCKER_PROJECT_DIR}/.env
    networks:
      - app_net

  mysql:
    container_name: ${PROJECT_NAME}-mysql
    image: mysql:5.7
    ports:
      - "33:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
  app_net:
    external:
      name: app_net